apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlset
spec:
  serviceName: mysqlservice
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        #image: mysql
        image: acrdemodefender.azurecr.io/aksdemodefender
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: password
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: rootpass
        ports:
        - containerPort: 3306
          name: mysqlport
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
