version: '3.1'
services:
    db:
        build:
            context: ./mysql/
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
    
    php:
        build:
            context: ./php/
            dockerfile: Dockerfile
        ports:
            - 8088:80